export const FILE_TYPE = {
  S3D: 0,
  EQG: 1,
};

export const WLD_TYPE = {

};

export const knownZoneShortNames = [
  'qeynos',
  'qeynos2',
  'qrg',
  'qeytoqrg',
  'highpass',
  'highkeep',
  'freportn',
  'freportw',
  'freporte',
  'runnyeye',
  'qey2hh1',
  'northkarana',
  'southkarana',
  'eastkarana',
  'beholder',
  'blackburrow',
  'paw',
  'rivervale',
  'kithicor',
  'commons',
  'ecommons',
  'erudnint',
  'erudnext',
  'nektulos',
  'nektulos',
  'cshome',
  'lavastorm',
  'nektropos',
  'halas',
  'everfrost',
  'soldunga',
  'soldungb',
  'misty',
  'nro',
  'sro',
  'befallen',
  'oasis',
  'tox',
  'hole',
  'neriaka',
  'neriakb',
  'neriakc',
  'neriakd',
  'najena',
  'qcat',
  'innothule',
  'feerrott',
  'cazicthule',
  'oggok',
  'rathemtn',
  'lakerathe',
  'grobb',
  'aviak',
  'gfaydark',
  'akanon',
  'steamfont',
  'lfaydark',
  'crushbone',
  'mistmoore',
  'kaladima',
  'felwithea',
  'felwitheb',
  'unrest',
  'kedge',
  'guktop',
  'gukbottom',
  'kaladimb',
  'butcher',
  'oot',
  'cauldron',
  'airplane',
  'fearplane',
  'permafrost',
  'kerraridge',
  'paineel',
  'hateplane',
  'arena',
  'fieldofbone',
  'warslikswood',
  'soltemple',
  'droga',
  'cabwest',
  'swampofnohope',
  'firiona',
  'lakeofillomen',
  'dreadlands',
  'burningwood',
  'kaesora',
  'sebilis',
  'citymist',
  'skyfire',
  'frontiermtns',
  'overthere',
  'emeraldjungle',
  'trakanon',
  'timorous',
  'kurn',
  'erudsxing',
  'stonebrunt',
  'warrens',
  'karnor',
  'chardok',
  'dalnir',
  'charasis',
  'cabeast',
  'nurga',
  'veeshan',
  'veksar',
  'iceclad',
  'frozenshadow',
  'velketor',
  'kael',
  'skyshrine',
  'thurgadina',
  'eastwastes',
  'cobaltscar',
  'greatdivide',
  'wakening',
  'westwastes',
  'crystal',
  'necropolis',
  'templeveeshan',
  'sirens',
  'mischiefplane',
  'growthplane',
  'sleeper',
  'thurgadinb',
  'erudsxing2',
  'shadowhaven',
  'bazaar',
  'bazaar',
  'nexus',
  'echo',
  'acrylia',
  'sharvahl',
  'paludal',
  'fungusgrove',
  'vexthal',
  'sseru',
  'katta',
  'netherbian',
  'ssratemple',
  'griegsend',
  'thedeep',
  'shadeweaver',
  'hollowshade',
  'grimling',
  'mseru',
  'letalis',
  'twilight',
  'thegrey',
  'tenebrous',
  'maiden',
  'dawnshroud',
  'scarlet',
  'umbral',
  'akheva',
  'arena2',
  'jaggedpine',
  'nedaria',
  'tutorial',
  'load',
  'load2',
  'hateplaneb',
  'shadowrest',
  'tutoriala',
  'tutorialb',
  'clz',
  'codecay',
  'pojustice',
  'poknowledge',
  'potranquility',
  'ponightmare',
  'podisease',
  'poinnovation',
  'potorment',
  'povalor',
  'bothunder',
  'postorms',
  'hohonora',
  'solrotower',
  'powar',
  'potactics',
  'poair',
  'powater',
  'pofire',
  'poeartha',
  'potimea',
  'hohonorb',
  'nightmareb',
  'poearthb',
  'potimeb',
  'gunthak',
  'dulak',
  'torgiran',
  'nadox',
  'hatesfury',
  'guka',
  'ruja',
  'taka',
  'mira',
  'mmca',
  'gukb',
  'rujb',
  'takb',
  'mirb',
  'mmcb',
  'gukc',
  'rujc',
  'takc',
  'mirc',
  'mmcc',
  'gukd',
  'rujd',
  'takd',
  'mird',
  'mmcd',
  'guke',
  'ruje',
  'take',
  'mire',
  'mmce',
  'gukf',
  'rujf',
  'takf',
  'mirf',
  'mmcf',
  'gukg',
  'rujg',
  'takg',
  'mirg',
  'mmcg',
  'gukh',
  'rujh',
  'takh',
  'mirh',
  'mmch',
  'ruji',
  'taki',
  'miri',
  'mmci',
  'rujj',
  'takj',
  'mirj',
  'mmcj',
  'chardokb',
  'soldungc',
  'abysmal',
  'natimbi',
  'qinimi',
  'riwwi',
  'barindu',
  'ferubi',
  'snpool',
  'snlair',
  'snplant',
  'sncrematory',
  'tipt',
  'vxed',
  'yxtta',
  'uqua',
  'kodtaz',
  'ikkinz',
  'qvic',
  'inktuta',
  'txevu',
  'tacvi',
  'qvicb',
  'wallofslaughter',
  'bloodfields',
  'draniksscar',
  'causeway',
  'chambersa',
  'chambersb',
  'chambersc',
  'chambersd',
  'chamberse',
  'chambersf',
  'provinggrounds',
  'anguish',
  'dranikhollowsa',
  'dranikhollowsb',
  'dranikhollowsc',
  'dranikcatacombsa',
  'dranikcatacombsb',
  'dranikcatacombsc',
  'draniksewersa',
  'draniksewersb',
  'draniksewersc',
  'riftseekers',
  'harbingers',
  'dranik',
  'broodlands',
  'stillmoona',
  'stillmoonb',
  'thundercrest',
  'delvea',
  'delveb',
  'thenest',
  'guildlobby',
  'guildhall',
  'barter',
  'illsalin',
  'illsalina',
  'illsalinb',
  'illsalinc',
  'dreadspire',
  'drachnidhive',
  'drachnidhivea',
  'drachnidhiveb',
  'drachnidhivec',
  'westkorlach',
  'westkorlacha',
  'westkorlachb',
  'westkorlachc',
  'eastkorlach',
  'eastkorlacha',
  'shadowspine',
  'corathus',
  'corathusa',
  'corathusb',
  'nektulosa',
  'arcstone',
  'relic',
  'skylance',
  'devastation',
  'devastationa',
  'rage',
  'ragea',
  'takishruins',
  'takishruinsa',
  'elddar',
  'elddara',
  'theater',
  'theatera',
  'freeporteast',
  'freeportwest',
  'freeportsewers',
  'freeportacademy',
  'freeporttemple',
  'freeportmilitia',
  'freeportarena',
  'freeportcityhall',
  'freeporttheater',
  'freeporthall',
  'northro',
  'southro',
  'crescent',
  'moors',
  'stonehive',
  'mesa',
  'roost',
  'steppes',
  'icefall',
  'valdeholm',
  'frostcrypt',
  'sunderock',
  'vergalid',
  'direwind',
  'ashengate',
  'highpasshold',
  'commonlands',
  'oceanoftears',
  'kithforest',
  'befallenb',
  'highpasskeep',
  'innothuleb',
  'toxxulia',
  'mistythicket',
  'kattacastrum',
  'thalassius',
  'atiiki',
  'zhisza',
  'silyssar',
  'solteris',
  'barren',
  'buriedsea',
  'jardelshook',
  'monkeyrock',
  'suncrest',
  'deadbone',
  'blacksail',
  'maidensgrave',
  'redfeather',
  'shipmvp',
  'shipmvu',
  'shippvu',
  'shipuvu',
  'shipmvm',
  'mechanotus',
  'mansion',
  'steamfactory',
  'shipworkshop',
  'gyrospireb',
  'gyrospirez',
  'dragonscale',
  'lopingplains',
  'hillsofshade',
  'bloodmoon',
  'crystallos',
  'guardian',
  'steamfontmts',
  'cryptofshade',
  'dragonscaleb',
  'oldfieldofbone',
  'oldkaesoraa',
  'oldkaesorab',
  'oldkurn',
  'oldkithicor',
  'oldcommons',
  'oldhighpass',
  'thevoida',
  'thevoidb',
  'thevoidc',
  'thevoidd',
  'thevoide',
  'thevoidf',
  'thevoidg',
  'oceangreenhills',
  'oceangreenvillage',
  'oldblackburrow',
  'bertoxtemple',
  'discord',
  'discordtower',
  'oldbloodfield',
  'precipiceofwar',
  'olddranik',
  'toskirakk',
  'korascian',
  'rathechamber',
  'brellsrest',
  'fungalforest',
  'underquarry',
  'coolingchamber',
  'shiningcity',
  'arthicrex',
  'foundation',
  'lichencreep',
  'pellucid',
  'stonesnake',
  'brellstemple',
  'convorteum',
  'brellsarena',
  'weddingchapel',
  'weddingchapeldark',
  'dragoncrypt',
  'feerrott2',
  'thulehouse1',
  'thulehouse2',
  'housegarden',
  'thulelibrary',
  'well',
  'fallen',
  'morellcastle',
  'somnium',
  'alkabormare',
  'miragulmare',
  'thuledream',
  'neighborhood',
  'argath',
  'arelis',
  'sarithcity',
  'rubak',
  'beastdomain',
  'resplendent',
  'pillarsalra',
  'windsong',
  'cityofbronze',
  'sepulcher',
  'eastsepulcher',
  'westsepulcher',
  'shardslanding',
  'xorbb',
  'kaelshard',
  'eastwastesshard',
  'crystalshard',
  'breedinggrounds',
  'eviltree',
  'grelleth',
  'chapterhouse',
  'arttest',
  'fhalls',
  'apprentice'
];

export const expansions = [
  'Original',
  'The Ruins of Kunark',
  'The Scars of Velious',
  'The Shadows of Luclin',
  'The Planes of Power',
  'The Legacy of Ykesha',
  'Lost Dungeons of Norrath',
  'Gates of Discord',
  'Omens of War',
  'Dragons of Norrath',
  'Depths of Darkhollow',
  'Prophecy of Ro',
  'The Serpent\'s Spine',
  'The Buried Sea',
  'Secrets of Faydwer',
  'Seeds of Destruction',
  'Underfoot',
  'House of Thule',
  'Veil of Alaris',
  'Rain of Fear',
  'Call of the Forsaken',
  'The Darkened Sea',
  'The Broken Mirror',
  'Empires of Kunark',
  'Ring of Scale',
  'The Burning Lands',
  'Torment of Velious',
  'Claws of Veeshan',
  'Terror of Luclin',
  'Night of Shadows',
  'Laurion\'s Song',
];

export const modelDefinitions = {
  avi        : 'Aviak',
  baf        : 'Barbarian Female',
  bam        : 'Barbarian Male',
  bat        : 'Bat',
  bea        : 'Bear',
  bet        : 'Beetle',
  bgm        : 'Beggar Male',
  caz        : 'Cazic-Thule',
  daf        : 'Dark Elf Female',
  daf01      : 'Dark Elf Female (Robe)',
  dam        : 'Dark Elf Male',
  dam01      : 'Dark Elf Male (Robe)',
  dwf        : 'Dwarf Female',
  dwm        : 'Dwarf Male',
  ele        : 'Mage Elemental',
  elf        : 'Wood Elf Female',
  elm        : 'Wood Elf Male',
  efr        : 'Efreeti',
  erf        : 'Erudite Female',
  erf01      : 'Erudite Female (Robe)',
  erm        : 'Erudite Male',
  erm01      : 'Erudite Male (Robe)',
  fpm        : 'Freeport Citizen (Male)',
  gnf        : 'Gnome Female',
  gnf01      : 'Gnome Female (Robe)',
  gnm        : 'Gnome Male',
  gnm01      : 'Gnome Male (Robe)',
  gnn        : 'Gnoll',
  gob        : 'Goblin',
  gol        : 'Golem',
  haf        : 'Half Elf Female',
  ham        : 'Half Elf Male',
  hif        : 'High Elf Female',
  hif01      : 'High Elf Female (Robe)',
  him        : 'High Elf Male',
  him01      : 'High Elf Male (Robe)',
  hof        : 'Halfling Female',
  hom        : 'Halfling Male',
  huf        : 'Human Female',
  huf01      : 'Human Female (Robe)',
  hum        : 'Human Male',
  hum01      : 'Human Male (Robe)',
  imp        : 'Imp',
  inn        : 'Innoruuk',
  ogf        : 'Ogre Female',
  ogm        : 'Ogre Male',
  orc        : 'Orc',
  pir        : 'Piranha',
  qcf        : 'Qeynos Citizen Female',
  qcm        : 'Qeynos Citizen Male',
  rat        : 'Rat',
  ske        : 'Skeleton',
  sna        : 'Snake',
  trf        : 'Troll Female',
  trm        : 'Troll Male',
  wer        : 'Werewolf',
  wil        : 'Willowisp',
  woe        : 'Wolf Elemental',
  wol        : 'Wolf',
  zof        : 'Zombie Female',
  zom        : 'Zombie Male',
  beh        : 'Evil Eye',
  cub        : 'Gelatinous Cube',
  den        : 'Amygdalan Knight',
  dru        : 'Dracholiche',
  frg        : 'Froglok (No Armor)',
  ghu        : 'Ghoul',
  gor        : 'Gorilla',
  grg        : 'Gorgon',
  rea        : 'Reanimated Hand',
  sca        : 'Scarecrow',
  spe        : 'Spectre',
  spi        : 'Spider',
  ten        : 'Tentacle Terror',
  uni        : 'Unicorn',
  dvm        : 'Maestro of Rancor',
  gar        : 'Gargoyle',
  mim        : 'Mimic',
  vsf        : 'Vampire Female',
  vsm        : 'Vampire Male',
  all        : 'Alligator',
  was        : 'Wasp',
  tre        : 'Treant',
  tig        : 'Tiger',
  sph        : 'Sphinx',
  sku        : 'Skunk',
  bix        : 'Bixie',
  brf        : 'Brownie Female',
  brm        : 'Brownie Male',
  cen        : 'Centaur',
  clf        : 'Clockwork Female',
  clm        : 'Clockwork Male',
  cpf        : 'Kerran Female',
  cpm        : 'Kerran Male',
  der        : 'Whirling Dervish',
  dji        : 'Djinn',
  dra        : 'Dragon',
  dri        : 'Shimmering Drake',
  drk        : 'Drake',
  egm        : 'Erudin Guard Male',
  faf        : 'Faerie',
  fro        : 'Froglok',
  fun        : 'Fungusman',
  gdm        : 'Ghost Dwarf Male',
  gia        : 'Giant / Cyclops',
  gri        : 'Griffon',
  har        : 'Harpy',
  hhm        : 'Highpass Guard',
  hlf        : 'Halas Citizen Female',
  hlm        : 'Halas Citizen Male',
  kob        : 'Kobold',
  lif        : 'Lioness',
  lim        : 'Lion',
  liz        : 'Lizardman',
  mam        : 'Elephant',
  min        : 'Minotaur',
  ngm        : 'Comonlands Guard',
  peg        : 'Pegasus',
  pif        : 'Pixie',
  pre        : 'Boat',
  pum        : 'Puma',
  rif        : 'Rivervale Citizen Female',
  rim        : 'Rivervale Citizen Male',
  sha        : 'Shark',
  aelobject02: 'Air Elemental',
  bri        : 'Bristlebane',
  eelmesh    : 'Earth Elemental',
  ero        : 'Erollisi Marr',
  fel01      : 'Fire Elemental',
  hsmmesh    : 'Horse',
  ikf        : 'Iksar Female',
  ikf01      : 'Iksar Female (Robe)',
  ikm        : 'Iksar Male',
  ikm01      : 'Iksar Male (Robe)',
  iks        : 'Iksar Skeleton',
  kef        : 'Vah Shir Female',
  kem        : 'Vah Shir Male',
  ral        : 'Rallos Zek',
  skemesh    : 'Skeleton',
  sol        : 'Solusek',
  tigmesh    : 'Tiger Mesh',
  tri        : 'Tribunal',
  tun        : 'Tunare',
  wel        : 'Water Elemental',
  woemesh    : 'Wolf Elemental Mesh',
  wof        : 'Chokidai',
  wolmesh    : 'Wolf Mesh',
  yet        : 'Yeti',
  arm        : 'Armadillo',
  bac        : 'Barracuda',
  bgg        : 'Goblin 2',
  brn        : 'Burynai',
  cl         : 'Clockwork Santa?',
  coc        : 'Cockatrice',
  dev        : 'Ravenous Nibbler',
  dml        : 'Iksar Skeleton Dervish',
  drf        : 'Drachnid Female',
  drm        : 'Drachnid Male',
  els        : 'Boat 2',
  fdr        : 'Fae Drake',
  fef        : 'Felwithe Citizen Female',
  fem        : 'Felwithe Citizen Male',
  fgi        : 'Forest Giant',
  frt        : 'Froglok Tadpole',
  gef        : 'Ghost Erudite Female',
  gem        : 'Ghost Erudite Male',
  gff        : 'Kelethin Citizen Female',
  gfm        : 'Kelethin Citizen Male',
  goo        : 'Goo',
  grf        : 'Grobb Citizen Female',
  grm        : 'Grobb Citizen Male',
  icf        : 'Cabilis Citizen Female',
  icm        : 'Cabilis Citizen Male',
  icn        : 'Iksar Guard',
  ikg        : 'Golem',
  ikh        : 'Evil Hand',
  ka         : 'Kaladim King',
  kaf        : 'Kaladim Citizen Female',
  kam        : 'Kaladim Citizen Male',
  ked        : 'Phinigel Autropos',
  kgo        : 'Goblin 3',
  lee        : 'Leech',
  luj        : 'Lycanthrope',
  lyc        : 'Drolvarg',
  mep        : 'Plant',
  mer        : 'Mermaid',
  mos        : 'Mosquito',
  okf        : 'Oggok Citizen Female',
  okm        : 'Oggok Citizen Male',
  rap        : 'Raptor',
  scr        : 'Scorpion',
  sed        : 'Evil Leech',
  sgo        : 'City of Mist Golem',
  sim        : 'Iksar Ghost Male',
  srw        : 'Sarnak Warrior',
  ssk        : 'Sarnak Skeleton',
  stu        : 'Sea Turtle',
  swo        : 'Swordfish',
  trk        : 'Trakanon',
  vrm        : 'Ratman',
  vst        : 'Venril Sathir',
  wur        : 'Wurm',
  xal        : 'Xalgoz',
  sea        : 'Seahorse',
  trn        : 'Evil Treant',
  wyv        : 'Wyvern',
  rhi        : 'Rhino',
  ogs        : 'Boat 3',
  bwd        : 'Dragon 2',
  isc        : 'Skorpikis',
  suc        : 'Succulent/Cactus',
  stc        : 'Sabertooth Cat',
  ccd        : 'Clockwork Dragon',
  cst        : 'Treasure Chest',
  dr2        : 'Dragon 3',
  gd3        : 'Phara Dar'

};
export const VERSION = 1.96;
