/**
 *
 * @param {import('@babylonjs/core').AnimationGroup[]} animationGroups
 */
export const mapAnimations = (animationGroups) => {
  const map = {};
  animationGroups.forEach((ag) => {
    const name = ag.name.replace('Clone of ', '');
    map[AnimationNames[name]] = ag;
  });
  return map;
};



export const AnimationNames = {
  Stand                  : 39,
  Sit_Stand              : 38,
  'Shuffle Feet'         : 33,
  Float_Walk_Strafe      : 33,
  Swim                   : 10,
  Sitting                : 38,
  'Stand (Arms at Sides)': 39,
  'p01'                  : 17,
  'Idle (Arms at Sides)' : 18,
  'Idle (Sitting)'       : 38,
  Walk                   : 41,
  Run                    : 40,
  'Jump (Running)'       : 19,
  'Jump (Standing)'      : 20,
  Falling                : 14,
  'Crouch Walk'          : 22,
  Climbing               : 23,
  Crouching              : 24,
  'Swim Treading'        : 25,
  'Combat Kick'          : 1,
  'Combat Piercing'      : 2,
  'Combat 2H Slash'      : 3,
  'Combat 2H Blunt'      : 4,
  'Combat Throwing'      : 5,
  'Combat 1H Slash Left' : 8,
  'Combat Bash'          : 7,
  'Combat Hand to Hand'  : 8,
  'Combat Archery'       : 9,
  'Combat Swim Attack'   : 8,
  'Combat Round Kick'    : 11,
  'Damage 1'             : 12,
  'Damage 2'             : 13,
  Drowning_Burning       : 15,
  Dying                  : 16,
  'Stringed Instrument'  : 51,
  'Wind Instrument'      : 51,
  'Cast Pull Back'       : 42,
  'Raise and Loop Arms'  : 43,
  'Cast Push Forward'    : 44,
  'Flying Kick'          : 45,
  'Rapid Punches'        : 46,
  'Large Punch'          : 47,
  Cheer                  : 27,
  Mourn                  : 28,
  Wave                   : 29,
  Rude                   : 30,
  Yawn                   : 31,
  Nod                    : 48,
  Amazed                 : -1,
  Plead                  : 50,
  Clap                   : 51,
  Distress               : 52,
  Blush                  : 52,
  Chuckle                : 54,
  Burp                   : 57,
  Duck                   : 22,
  'Look Around'          : 57,
  Dance                  : 58,
  Blink                  : 59,
  Glare                  : 60,
  Drool                  : 60,
  Kneel                  : 62,
  Laugh                  : 63,
  Point                  : 64,
  Ponder                 : 65,
  Ready                  : 66,
  Salute                 : 67,
  Shiver                 : 68,
  'Tap Foot'             : 69,
  Bow                    : 70,
};

export const loopedAnimations = [
  AnimationNames.Stand,
  AnimationNames.Walk,
  AnimationNames.Run,
  AnimationNames.Falling,
  AnimationNames['Crouch Walk'],
  AnimationNames.Climbing,
  AnimationNames['Swim Treading'],
  AnimationNames['Shuffle Feet'],
  AnimationNames.Swim,
  AnimationNames.Sitting,
  AnimationNames['Stand (Arms at Sides)']
];

// const std:: map<std:: string, int> animations = {
// 	{ "kick", 1 },
// { "pierce", 2 },
// { "2hslash", 3 },
// { "2hblunt", 4 },
// { "2hpierce", 4 },
// { "throw", 5 },
// { "offhand", 6 },
// { "bash", 7 },
// { "mainhand", 8 },
// { "bow", 9 },
// { "swim", 10 },
// { "roundkick", 11 },
// { "gethit", 12 },
// { "gethit2", 13 },
// { "falling", 14 },
// { "drowning", 15 },
// { "death", 16 },
// { "standby", 17 },
// { "standby2", 18 },
// { "lunge", 19 },
// { "jump", 20 },
// { "falling2", 21 },
// { "duckwalk", 22 },
// { "ladderclimb", 23 },
// { "crouch", 24 },
// { "swim2", 25 },
// { "idle", 26 },
// { "cheer", 27 },
// { "disgusted", 28 },
// { "wave", 29 },
// { "rude", 30 },
// { "yawn", 31 },
// { "movetoside", 33 },
// { "iceslide", 35 },
// { "kneel", 36 },
// { "swim3", 37 },
// { "sit", 38 },
// { "cast", 42 },
// { "cast2", 43 },
// { "cast3", 44 },
// { "flykick", 45 },
// { "tigerclaw", 46 },
// { "eaglestrike", 47 },
// { "nodyes", 48 },
// { "shakeno", 49 },
// { "plead", 50 },
// { "clap", 51 },
// { "blush", 52 },
// { "chuckle", 54 },
// { "headtilt", 57 },
// { "dance", 58 },
// { "disagree", 59 },
// { "glare", 60 },
// { "peer", 61 },
// { "kneel", 62 },
// { "laugh", 63 },
// { "point", 64 },
// { "shrug", 65 },
// { "handraise", 66 },
// { "salute", 67 },
// { "shiver", 68 },
// { "tapfoot", 69 },
// { "bowto", 70 }
// };

// const std:: map<int, std:: string> animation_names_map = {
//     { 1, "Kick" },
//     { 2, "1H Piercing" },
//     { 3, "2H Slashing" },
//     { 4, "2H Blunt" },
//     { 4, "2H Piercing" },
//     { 5, "Throw" },
//     { 6, "Off Hand" },
//     { 7, "Bash" },
//     { 8, "Main Hand" },
//     { 9, "Bow" },
//     { 10, "Swim" },
//     { 11, "Round Kick" },
//     { 12, "Get Hit" },
//     { 13, "Get Hit" },
//     { 14, "Falling" },
//     { 15, "Drowning" },
//     { 16, "Death" },
//     { 17, "Stand By" },
//     { 18, "Stand By" },
//     { 19, "Lunge" },
//     { 20, "Jump" },
//     { 21, "Falling" },
//     { 22, "Crouched Walk" },
//     { 23, "Ladder Climb" },
//     { 24, "Crouch" },
//     { 25, "Swim" },
//     { 26, "Idle" },
//     { 27, "Cheer" },
//     { 28, "Disgusted" },
//     { 29, "Wave" },
//     { 30, "Rude" },
//     { 31, "Yawn" },
//     { 33, "Move To Side" },
//     { 35, "Ice Slide" },
//     { 36, "Kneel" },
//     { 37, "Swim" },
//     { 38, "Sit" },
//     { 42, "Cast" },
//     { 43, "Cast" },
//     { 44, "Cast" },
//     { 45, "Flying Kick" },
//     { 46, "Tiger Claw" },
//     { 47, "Eagle Strike" },
//     { 48, "Nod Yes" },
//     { 49, "Shake No" },
//     { 50, "Plead" },
//     { 51, "Clap" },
//     { 52, "Blush" },
//     { 54, "Chuckle" },
//     { 57, "Head Tilt" },
//     { 58, "Dance" },
//     { 59, "Disagree" },
//     { 60, "Glare" },
//     { 61, "Peer" },
//     { 62, "Kneel" },
//     { 63, "Laugh" },
//     { 64, "Point" },
//     { 65, "Shrug" },
//     { 66, "Hand Raise" },
//     { 67, "Salute" },
//     { 68, "Shiver" },
//     { 69, "Tap Foot" },
//     { 70, "Bow To" }
// };
