name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

env:
  # Set the release version from the Git tag (e.g. v1.2.3)
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "Building for macOS (arm64)..."
            npm run build:electron:mac
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Building for Windows (x64)..."
            npm run build:electron:win
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "Building for Linux (x64)..."
            npm run build:electron:linux
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # Adjust the artifact path if needed (here we assume electron-builder outputs to "dist")
          name: build-${{ matrix.os }}
          path: dist/**

  release:
    name: Create Release and Upload Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          # All artifacts will be downloaded under the "build-artifacts" folder
          path: build-artifacts

      - name: Create Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          title: "${{ env.VERSION }}"
          # Adjust the file paths below to match the artifacts uploaded.
          files: |
            build-artifacts/**
